language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: 'true'
deploy:
- provider: script
  script: "./devel/travis_deploy.sh"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: NQdrb8qfSbS82qTj1OHlpBsX2Y0uT5Gg4stxDzaLmwOzUjB6d7kI1y/uLagfYrGknCaWWPrGZ+pQffPanKCjLzrkTy/WtsSaDIdksuNFCC0PFwxaNfRrO36GbwyL2ieoTQtxqw7wDpG1BCpzLX29Mrr3apLGo9LsaOyAPHjsXy0LBaXOLMQjH5DVKwgsjWyToz1G3+vttamlGT4sKkvL95gmspfRb8YgfDLIggLNmbF/l9H0tZPLt+w06JA9I728Vwd3UWydi3B4kGGfiMFDzHg1m+alCMvTFH/slWDOGsTsnZLQlGSXbnlxrYtkkXR/57uaypkIERP5KehlVK0vG+SpeEwMiXtlBb3TDIyTgOXXfpf/FF/yO8Fq+GYzaVpl0weH4AjW8PnY0py0zpVHeBrmQiYpBk/UaAkhTckHh7oYVyLhkhlogao2O8wVPG1m0H6QwiTvAR8fOIJ9b0eNt4q+IsUlL9Xqeivp/ZnOov20qis/KJc4+DyDwzx4c4fSQwTHXnJgiXtu9BihZ6QS+BMh61N+IDqmQ4fRCZjfYXQ8NbFOMmnEWkta6NgkPr2rhT7Z/b6wJ4dAc1OwkxNLAgw4IvvAd1pzsPEjl1L5Bd3AaFWwNudTVkNJ4CkLYDlRWiIDiMIvCmnMFbOVI2w/G09sC1wThkL01mv2rRkpxJs=
  - secure: c72+u7saFAtdV7WHkfnj7N5RGvTdiW/ICf3NebYR6/WXkRC7QMY8BAWMJUrYQrGc2SytG5dDvS5inFytRm9UoeUt533sExTKeM7lUL/CF+QuxCswS6blwUSbP3N+Anff+9fwZFAgvvGfIynpGJD7xoNbuUZyPIiFEtSo/pLJqi2FHNsGqlJEtwzsgl0iCbQJJIniyGt01UdJ3Bh/wYoh8rW0OSbLOmu/tIcIkrb4o5tVYwJzXEXm21VQYQcNndtNCmC15LicAraH4tf+sH9Mgd7U2TGynK9zJcAqusGiYVA/h69qjGmcUbq9fZNL+FKpuAetAfI/Pn3Dm/GgPKurBxPQoLB66/kEIyBihG66y/HCUCLsPyD6GevFA8KHmdJ0Q/aEB2xheXC7TKqfYL6Qh0jHrUumGyCytnZanfjHBmxmgQ+Gsq28ucOI9nSa/9FCOuLenN/m4mnLfCqOoshtC6BMW6i6ge2dWXKwXyzH/HZFvWFqr+xdipnKstGmOZU09d5FPnvJLR3ekpjh8tHO2Yq89DjCBwvmgqBEX26aDN8nPvd+DAn3X1+zyRgeRVA3d2q/lfsyzmxsni3UtlkvvVl4719x28ywoGXDc16O5POn8AK7ad0a+DCfVA6IFXfjiafTeK7ghD3qw11A+Ksoyew5B5tcUYecwNw3oFmvAuA=
  - secure: hP8OvRo0kfAXzledMaY7FrU98UQSs1KdcSDVs/Sc+9N7UqbzKuh5LbcfneBVrdiJ9ZQ6lNRW73lzlIRbmowvGZCS7WcjZVakdpxIYcL+Ld9Mbtbl3TJbgeAq8Ttlf1JgBJajhUu55h9PQEM/0oFFLssrop3T7og28dnMpz3diNnoRUhsMpbx4H6uKVoxyFamq9iTaA6uVISbcxF0Chn78u/JEmHxBmOYNntiITG/lqZpW2MOC4RQdAyghVXwQ+r0vzdLcj2mTIFJHypaYymataK3pOld06gbK9VlzV2yXA8ShDy1kVtoblQr8TMm+XqBKlOkXvWma/8ji41X7py6JRkNGiToJBFjXYarr0UftR8611tZin5JL2Qvnl+mxBRldhK6/SPDMcp/QSlnUXZwVr8nrBIbxKQs9y7cX7B8WTbwnY7BUw4B6yp/l3uVuyb/Nr6evxyY7ZaI/qmRAbu8DZX/YT72X+P24+y5Ra2OpKPCjxe5WCuvCES8aAcYsdtAMK1uxfWEeeVhGNR4zwXCBuySCexNS54eaqkKG5niyrou6YYmUn53pgjDAcbIZ9m+AerxJX4DQVHS146dGSarDrAPUW6sfsFG0tZRTpSzpmXhpc91t198Ea/qS5UNK9oL0i/K80u2MkjHIs6Uw9d1f04+N7aYbmb8tJAjOlC9Xhw=
